table 'Days Parameter'
	lineageTag: 4e01f083-466f-4610-b2b8-35263f2629ea

	measure 'Days Parameter Value' = SELECTEDVALUE('Days Parameter'[Days Parameter], 15)
		formatString: 0
		lineageTag: e766eb63-69e9-4490-a672-b924155242ba

	column 'Days Parameter'
		formatString: 0
		lineageTag: be2ce577-21f8-420d-92da-b5fa3632738e
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'Days Parameter' = calculated
		mode: import
		source = GENERATESERIES(1, 30, 1)

	annotation PBI_Id = abf7e567d45740699ece9b1227bcea14

