table result_occupancy
	lineageTag: 308a1875-e5c9-444b-9a9c-02dc93230776

	column Facility
		dataType: string
		lineageTag: d248b18f-1e44-49bb-a665-2a25860d3991
		summarizeBy: none
		sourceColumn: Facility

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 1f8ad7c2-1bc6-4099-a1c5-69d07dde4efc
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column '# Units'
		dataType: int64
		formatString: 0
		lineageTag: fb3f44c2-3c51-4737-a4ea-d20b29863c01
		summarizeBy: sum
		sourceColumn: # Units

		annotation SummarizationSetBy = Automatic

	column '# Occupied'
		dataType: int64
		formatString: 0
		lineageTag: a56995a3-bf3a-4bc3-8d75-c7bc424c9703
		summarizeBy: sum
		sourceColumn: # Occupied

		annotation SummarizationSetBy = Automatic

	column 'sq ft / unit'
		dataType: double
		lineageTag: 91cd7f35-eec3-4191-a3fc-99ee6006accd
		summarizeBy: sum
		sourceColumn: sq ft / unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'sq ft total'
		dataType: double
		lineageTag: 4c0e9b7f-ff86-4393-8d0b-ee171af7ace1
		summarizeBy: sum
		sourceColumn: sq ft total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Occupied sq ft'
		dataType: double
		lineageTag: cf818346-e60b-49db-856e-4f6f7f9d6c3e
		summarizeBy: sum
		sourceColumn: Occupied sq ft

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price
		dataType: double
		lineageTag: c8455791-b87d-445a-85c5-1f18626b8595
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg Actual Price'
		dataType: double
		lineageTag: 3a108e83-237f-40ad-bb29-efdebccca19b
		summarizeBy: sum
		sourceColumn: Avg Actual Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Physical Occupancy'
		dataType: double
		lineageTag: a4809989-ad8d-461c-8d37-fc868028a8f2
		summarizeBy: sum
		sourceColumn: Physical Occupancy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Area Occ'
		dataType: double
		lineageTag: 77737c1f-6f4c-4df6-afa7-1aee61def93f
		summarizeBy: sum
		sourceColumn: Area Occ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Economic Occ'
		dataType: double
		lineageTag: d1ac29de-1c8e-450c-b4b3-92c25b627383
		summarizeBy: sum
		sourceColumn: Economic Occ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GrossPotRent
		dataType: int64
		formatString: 0
		lineageTag: 9261f509-661f-455d-8bf4-b3b5ad8e2360
		summarizeBy: sum
		sourceColumn: GrossPotRent

		annotation SummarizationSetBy = Automatic

	column OccupiedRent
		dataType: double
		lineageTag: 31d4e58c-db72-4909-aa83-4a031f7ad3aa
		summarizeBy: sum
		sourceColumn: OccupiedRent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RPOSF
		dataType: double
		lineageTag: 5a33081c-07d1-408b-b5a2-13ebb3880b1a
		summarizeBy: sum
		sourceColumn: RPOSF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RPSF
		dataType: double
		lineageTag: 1a05b8af-307a-468f-a52f-a4a25e2343ee
		summarizeBy: sum
		sourceColumn: RPSF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 87fec169-7906-4a27-b509-32c3c4f9e83e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Vacant Units' = result_occupancy[# Units]-result_occupancy[# Occupied]
		formatString: 0
		lineageTag: ac21a9fe-c5c1-44e7-93a0-fecaf9248ee4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition result_occupancy = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1g0WEqHCal_Xo-FbLNNuAX-PX_kjGhBt9g7O8_R-kyZY/edit?gid=440527405#gid=440527405"),
				    result_occupancy_Table = Source{[name="result_occupancy",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(result_occupancy_Table),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Facility", type text}, {"DateTime", type text}, {"Size", type text}, {"# Units", Int64.Type}, {"# Occupied", Int64.Type}, {"sq ft / unit", type number}, {"sq ft total", type number}, {"Occupied sq ft", type number}, {"Price", type number}, {"Avg Actual Price", type number}, {"Physical Occupancy", Percentage.Type}, {"Area Occ", Percentage.Type}, {"Economic Occ", Percentage.Type}, {"GrossPotRent", Int64.Type}, {"OccupiedRent", type number}, {"RPOSF", type number}, {"RPSF", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","-","",Replacer.ReplaceText,{"Facility"}),
				    #"Added Prefix" = Table.TransformColumns(#"Replaced Value", {{"Facility", each "Click Storage " & _, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Added Prefix",{{"DateTime", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"DateTime", Text.Trim, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Cleaned Text", "Date", each Text.Replace(Text.Replace([DateTime], "/", "-"), "-", "/")),
				    #"Changed Type 2" = Table.TransformColumnTypes(#"Added Custom",{{"Date", type text}}),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type 2", {{"Date", type date}}, "en-US"),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type with Locale1",{"DateTime"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each [Date] < #date(2023, 11, 14))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

